### ISSUE TITLE
How to train for X2,X3,X8

### ISSUE THREAD

**Issue by sandeep1671995** [open-mmlab/mmsr#56]
Hello,
I have trained X4 using the default yml file, but I am not able to change the configuration to train X2 , X3 or X8. Could please tell me where the changes needs to be made ?

**Comment by Dejan1969** [comment]
Hello I think that you must train SR model first

For X2:
Downscale HR images 2x
Modify the configuration file options/test/test_SRResNet.yml
Run command: python test.py -opt options/test/test_SRResNet.yml

My test_SRResNet.yml

```
# Not exactly the same as SRResNet in <Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network>
# With 16 Residual blocks w/o BN

#### general settings
name: MSRResNetx2_scratch_DF2K
use_tb_logger: true
model: sr
distortion: sr
scale: 2
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DF2K2
    mode: LQGT
    dataroot_GT: /home/xxxxxx/datasets/DF2K_train_HR_2X_sub
    dataroot_LQ: /home/xxxxxx/datasets/DF2K_train_LR_2X_sub

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K2
    mode: LQGT
    dataroot_GT: /home/xxxxxx/datasets/DF2K_valid_HR
    dataroot_LQ: /home/xxxxxx/datasets/DF2K_valid_LR_2X

#### network structures
network_G:
  which_model_G: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
```
Hope this help
